r = +prompt('Введите радиус цилиндра R');
h = +prompt('Введите высоту цилиндра H');
s = +prompt('Введите площадь основы цилиндра');
v = Math.PI*r*r*h;
document.write("<p>**************</p>");
document.write("<p>Обьем цилиндра с площадью основы "+s+", радиусом "+r+" и высотой "+h+" равен:</p>");
document.write("<p>--------------------</p>");
document.write("<p>V = "+v+".</p>");
document.write("<p>-------------------</p>");
document.write("<p>end.</p>");